apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: myapp
build:
  artifacts:
  - image: ivekov/ivekov
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
    - ingress.yaml