apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: mynginx
build:
  artifacts:
  - image: ivekov/nginx-8000
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
    - ingress.yaml